In [2]:
import torch

In [10]:
x1 = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
x2 = torch.tensor([[10.0, 100], [1000, 10000]])

x21 = torch.stack((x1, 2*x1))
x22 = torch.stack((x2, -1*x2))

In [11]:
torch.bmm(x21, x22)

tensor([[[  2010.,  20100.],
         [  4030.,  40300.]],

        [[ -4020., -40200.],
         [ -8060., -80600.]]])

In [15]:
torch.mul(x21, x22)

tensor([[[ 1.0000e+01,  2.0000e+02],
         [ 3.0000e+03,  4.0000e+04]],

        [[-2.0000e+01, -4.0000e+02],
         [-6.0000e+03, -8.0000e+04]]])

In [22]:
pzxs = torch.tensor([1.0, 3.0]).unsqueeze(1).unsqueeze(2) * torch.mul(x21, x22)
pzxs

tensor([[[ 1.0000e+01,  2.0000e+02],
         [ 3.0000e+03,  4.0000e+04]],

        [[-6.0000e+01, -1.2000e+03],
         [-1.8000e+04, -2.4000e+05]]])

In [25]:
pz_given_xs_sum = torch.sum(pzxs, 0)
pz_given_xs_sum

tensor([[-5.0000e+01, -1.0000e+03],
        [-1.5000e+04, -2.0000e+05]])

In [26]:
1/pz_given_xs_sum

tensor([[-2.0000e-02, -1.0000e-03],
        [-6.6667e-05, -5.0000e-06]])

In [36]:
t01 = torch.tensor([0., 1])
t01[t01.eq(0)] = 1
t01

tensor([1., 1.])

In [39]:
pzxs * torch.tensor([[1., 0],[0., 1]])

tensor([[[ 1.0000e+01,  0.0000e+00],
         [ 0.0000e+00,  4.0000e+04]],

        [[-6.0000e+01, -0.0000e+00],
         [-0.0000e+00, -2.4000e+05]]])

In [40]:
torch.ones(10)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [42]:
import plsa

ModuleNotFoundError: No module named 'plsa'