In [2]:
import torch

In [10]:
x1 = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
x2 = torch.tensor([[10.0, 100], [1000, 10000]])

x21 = torch.stack((x1, 2*x1))
x22 = torch.stack((x2, -1*x2))

In [11]:
torch.bmm(x21, x22)

tensor([[[  2010.,  20100.],
         [  4030.,  40300.]],

        [[ -4020., -40200.],
         [ -8060., -80600.]]])

In [15]:
torch.mul(x21, x22)

tensor([[[ 1.0000e+01,  2.0000e+02],
         [ 3.0000e+03,  4.0000e+04]],

        [[-2.0000e+01, -4.0000e+02],
         [-6.0000e+03, -8.0000e+04]]])

In [22]:
pzxs = torch.tensor([1.0, 3.0]).unsqueeze(1).unsqueeze(2) * torch.mul(x21, x22)
pzxs

tensor([[[ 1.0000e+01,  2.0000e+02],
         [ 3.0000e+03,  4.0000e+04]],

        [[-6.0000e+01, -1.2000e+03],
         [-1.8000e+04, -2.4000e+05]]])

In [25]:
pz_given_xs_sum = torch.sum(pzxs, 0)
pz_given_xs_sum

tensor([[-5.0000e+01, -1.0000e+03],
        [-1.5000e+04, -2.0000e+05]])

In [26]:
1/pz_given_xs_sum

tensor([[-2.0000e-02, -1.0000e-03],
        [-6.6667e-05, -5.0000e-06]])

In [36]:
t01 = torch.tensor([0., 1])
t01[t01.eq(0)] = 1
t01

tensor([1., 1.])

In [39]:
pzxs * torch.tensor([[1., 0],[0., 1]])

tensor([[[ 1.0000e+01,  0.0000e+00],
         [ 0.0000e+00,  4.0000e+04]],

        [[-6.0000e+01, -0.0000e+00],
         [-0.0000e+00, -2.4000e+05]]])

In [40]:
torch.ones(10)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [48]:
import importlib

In [55]:
import plsa


<module 'plsa' from 'd:\\data\\gitrepo\\plsa\\plsa.py'>

In [250]:
importlib.reload(plsa)
p = plsa.PLSA([[1,2, 3],[3,4, 5]], 4)

In [146]:
print(p.data)
print(p.init_pxi_given_zs)
print(plsa.unsqueeze_ot(torch.tensor([0, 1]), 1, 2))

tensor([[1., 2., 3.],
        [3., 4., 5.]])
[tensor([[0.2500, 0.2500],
        [0.2500, 0.2500],
        [0.2500, 0.2500],
        [0.2500, 0.2500]]), tensor([[0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500]])]
tensor([[0, 1]])


In [122]:
import functools

In [153]:
t01 = [plsa.unsqueeze_ot(p.pxi_given_zs[i], [0,i+1], 3) for i in range(len(p.pxi_given_zs))]
print(t01)
t02 = [plsa.unsqueeze_ot(torch.ones(4), [0], 3)]+ t01
print([m.size() for m in t02])
functools.reduce(torch.mul, t02[1:], t02[0]).size()

[tensor([[[0.2500],
         [0.2500]],

        [[0.2500],
         [0.2500]],

        [[0.2500],
         [0.2500]],

        [[0.2500],
         [0.2500]]]), tensor([[[0.2500, 0.2500, 0.2500]],

        [[0.2500, 0.2500, 0.2500]],

        [[0.2500, 0.2500, 0.2500]],

        [[0.2500, 0.2500, 0.2500]]])]
[torch.Size([4, 1, 1]), torch.Size([4, 2, 1]), torch.Size([4, 1, 3])]


torch.Size([4, 2, 3])

In [157]:
t01 = [0, 1, 2].remove(1)

In [104]:
t01 = torch.tensor([1, 2])
t02 = t01.clone()
plsa.unsqueeze_ot(t01, 1, 2)
t02

tensor([1, 2])

In [70]:
def randtest():
    ds = (3,4,5)
    return torch.rand(*ds)

randtest()
randtest().size()
(1,)+(*(randtest().size()),)

(1, 3, 4, 5)

In [77]:
torch.sum(p.data, dim=())

tensor(10.)

In [86]:
p.data / torch.sum(p.data, dim=1, keepdim=True)

tensor([[0.3333, 0.6667],
        [0.4286, 0.5714]])

In [89]:
p.data.unsqueeze(p.data.dim())

tensor([[[1.],
         [2.]],

        [[3.],
         [4.]]])

In [92]:
torch.tensor([1,2]).unsqueeze_(0)

tensor([[1, 2]])

In [251]:
p1 = plsa.PLSA(torch.tensor([[3, 0, 0], [1, 0, 0], [0, 1, 1]]), 2)

In [252]:
p1.pz

tensor([0.5000, 0.5000])

In [253]:
p1.em_algorithm(10)

In [254]:
p1.pz_given_xs

tensor([[[1., 0., 0.],
         [1., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 1., 1.]]])

In [255]:
p1.pxi_given_zs

[tensor([[0.7500, 0.2500, 0.0000],
         [0.0000, 0.0000, 1.0000]]), tensor([[1.0000, 0.0000, 0.0000],
         [0.0000, 0.5000, 0.5000]])]

In [ ]:



[-]





In [249]:
[(100*m).round() for m in p1.pxi_given_zs]

[tensor([[ 75.,  25.,   0.],
         [  0.,   0., 100.]]), tensor([[100.,   0.,   0.],
         [  0.,  50.,  50.]])]

In [236]:
p1.pz

tensor([0.3851, 0.6149])

In [190]:
p1.pxi_given_zs[0][0].ger(p1.pxi_given_zs[1][0])

tensor([[0.3061, 0.0612, 0.0612],
        [0.1020, 0.0204, 0.0204],
        [0.3061, 0.0612, 0.0612]])

In [197]:
p1.pxi_given_zs[0][1].ger(p1.pxi_given_zs[1][1])

tensor([[0.3061, 0.0612, 0.0612],
        [0.1020, 0.0204, 0.0204],
        [0.3061, 0.0612, 0.0612]])

In [209]:
p1.tmp

tensor([[[1.0000, 0.0000, 0.0000],
         [0.3333, 0.0000, 0.0000],
         [0.3333, 0.3333, 0.3333]],

        [[2.0000, 0.0000, 0.0000],
         [0.6667, 0.0000, 0.0000],
         [0.6667, 0.6667, 0.6667]]])

In [202]:
plsa.normalize(p1.pzxs, [1,2])

tensor([[[0.3061, 0.0612, 0.0612],
         [0.1020, 0.0204, 0.0204],
         [0.3061, 0.0612, 0.0612]],

        [[0.3061, 0.0612, 0.0612],
         [0.1020, 0.0204, 0.0204],
         [0.3061, 0.0612, 0.0612]]])

In [173]:
plsa.normalize(p1.tmp, [2])

tensor([[[1.0000, 0.0000, 0.0000],
         [1.0000, 0.0000, 0.0000],
         [0.3333, 0.3333, 0.3333]],

        [[1.0000, 0.0000, 0.0000],
         [1.0000, 0.0000, 0.0000],
         [0.3333, 0.3333, 0.3333]]])